openapi: 3.0.3

info:
  version: 1.0.0
  title: File Structure Interface
  description: File Structure

servers:
  - url: http://localhost:8080
    description: Dev-Instance.

paths:
  /userCreate:
    post:
      summary: 'Create a user structure'
      operationId: createUserStructure
      requestBody:
        description: Create a user structure
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserStructure'
      responses:
        200:
          $ref: '#/components/responses/Response'

components:
  schemas:
    CreateUserStructure:
      type: object
      required:
        - issue
      properties:
        username:
          type: string
          nullable: false
        userId:
          type: integer
          nullable: false
        transactionDate:
          type: string
          format: date-time

  responses:
    ManualImportResponse:
      description: Response for manual import request
      content:
        application/json:
          schema:
            type: object
            properties:
              info:
                type: string
                nullable: false
                description: A description of what happened

    Response:
      description: Generic UpdateResponse
      content:
        application/json:
          schema:
            type: object
            properties:
              info:
                type: string
                nullable: false
                description: A description of what happened
